### ISSUE TITLE
동일한 단어의 다른 형태는 어떤식으로 하나용

### ISSUE THREAD

**Issue by sjs2109** [sjs2109/won-s_summary#1]
예를 들면 아키텍트와 architect는 같은 단어일까요 다른 단어일까요?

**Comment by masterofjisuk** [comment]
우선 다른뜻으로 처리 해주세요 이후 취합된내용으로 다시 분류하려구요

**Comment by sjs2109** [comment]
네 일단 다른 뜻으로 할께용 나중에 바뀌면 알려주세요
